name: Docker image pushed to render.com

on:
  push:
    branches:
      - develop
  #  pull_request:
  #    branches:
  #      - main
  #      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/lb-advisors/springboot:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_GH_TOKEN }}

      # to read: https://dev.to/onticdani/automatically-build-docker-images-with-github-actions-3n8e
      - name: Push the Docker image
        run: docker push ghcr.io/lb-advisors/springboot:latest

      - name: Archive JAR file
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar

      # trigger render.com docker image deployment
      - name: Deploy to Render
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_TRIGGER_URL }}
          method: "GET"
